<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-O60VPK0" failures="1" tests="3" name="LowPriorityTest" time="76.744" errors="0" timestamp="2022-10-10T09:48:02 IST">
  <testcase classname="com.Saucedemo.TestClasses.TC01_VerifyLoginFunctionality" name="loginfuctionality" time="1.228"/>
  <testcase classname="com.Saucedemo.TestClasses.TC06_ProceedToCheckOuProduct" name="verifyproceedtobuyfunctionality" time="6.513"/>
  <testcase classname="com.Saucedemo.TestClasses.TC02_LoginfunctionalityNegativeWay" name="verifyloginnegativefunctionality" time="2.908">
    <failure type="java.lang.AssertionError" message="expected [https://www.saucedemo.com/] but found [https://www.saucedemo.com/inventory.html]">
      <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/] but found [https://www.saucedemo.com/inventory.html]
at com.Saucedemo.TestClasses.TC02_LoginfunctionalityNegativeWay.verifyloginnegativefunctionality(TC02_LoginfunctionalityNegativeWay.java:25)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyloginnegativefunctionality -->
</testsuite> <!-- LowPriorityTest -->
